# Generated by Django 4.0.1 on 2022-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_blog_description_alter_blog_shdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='product', verbose_name='Product Image'),
        ),
    ]
