# Generated by Django 4.0.3 on 2022-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India'), ('Japan', 'Japan'), ('Saudi', 'Saudi'), ('America', 'America')], default='Nepal', max_length=50)),
                ('adderess1', models.CharField(max_length=100)),
                ('adderess2', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
