<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-04-15 05:16
=======
# Generated by Django 4.0.1 on 2022-04-13 02:20
>>>>>>> 29cc043dc844990bd62c6ec1124a253860fa1b8a

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contactenquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='adderess1',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='adderess2',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='town',
        ),
    ]
