# Generated by Django 3.2.3 on 2022-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_contactenquiry_adderess1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
