# Generated by Django 4.0.1 on 2022-04-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_contactenquiry_adderess1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='lname',
            new_name='reciver',
        ),
    ]
